[project]
name = "call-me-baby"
version = "0.1.0"
description = ""
authors = [
    {name = "lmongili"}
]
requires-python = ">=3.10"
dependencies = [
    "numpy (==1.26.0)",
    "llm-sdk",
    "accelerate>=1.15.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.uv]
cache-dir = "/home/lmongili/sgoinfre/call-me-baby/"
package = false

[tool.uv.sources]
llm_sdk = { workspace = true }

[tool.uv.workspace]
members = ["llm_sdk"]
